package net.moznion.jakotem;

public enum TokenType {
  RAW,
  OPEN, CLOSE,
  PLUS, MINUS, DIVIDE, MUL, MODULO,
  LE, LT, GE, GT, NE, NOT,
  FILE, LINE, ROOT,
  CONCAT,
  IDENT,
  STRING, INTEGER, DOUBLE, HEX, OCTAL, BINARY,
  CONDITIONAL, CONDITIONAL_SELECTOR, EQUAL, EQUALEQUAL,
  BIT_AND, BIT_OR, BIT_XOR,
  ANDAND, OROR, NULL_OR, PIPE,
  ARROW, COMMA,
  LBRACKET, RBRACKET, LBRACE, RBRACE, LPAREN, RPAREN,
  NIL, TRUE, FALSE, FOR, WHILE, MIN, MAX, IF, ELSE,
  SWITCH, CASE, INCLUDE, BLOCK, CASCADE, AROUND, BEFORE,
  AFTER, SUPER,
}
